In [ ]:
from numpy import argmax

In [ ]:
import pandas as pd


In [ ]:
from sklearn.datasets import load_iris

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
iris=load_iris()

In [ ]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
x=iris.data[:,:].astype('float32')
y=iris.target

In [ ]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [ ]:
n_feature=x_train.shape[1]
print('Number of Features:',n_feature)

Number of Features: 4


In [ ]:
model=Sequential()


In [ ]:
model.add(Dense(10,activation='relu',kernel_initializer='he_normal',input_shape=(n_feature,)))
model.add(Dense(8,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(3,activation='softmax'))

In [ ]:
model.compile(optimizer="adam",loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=150,batch_size=32)

Epoch 1/150
4/4 [==============================] - 1s 9ms/step - loss: 1.9601 - accuracy: 0.3571
Epoch 2/150
4/4 [==============================] - 0s 5ms/step - loss: 1.8487 - accuracy: 0.3571
Epoch 3/150
4/4 [==============================] - 0s 6ms/step - loss: 1.7445 - accuracy: 0.3571
Epoch 4/150
4/4 [==============================] - 0s 5ms/step - loss: 1.6499 - accuracy: 0.3571
Epoch 5/150
4/4 [==============================] - 0s 6ms/step - loss: 1.5615 - accuracy: 0.3571
Epoch 6/150
4/4 [==============================] - 0s 6ms/step - loss: 1.4810 - accuracy: 0.3571
Epoch 7/150
4/4 [==============================] - 0s 6ms/step - loss: 1.4106 - accuracy: 0.3571
Epoch 8/150
4/4 [==============================] - 0s 6ms/step - loss: 1.3511 - accuracy: 0.3571
Epoch 9/150
4/4 [==============================] - 0s 6ms/step - loss: 1.2922 - accuracy: 0.3571
Epoch 10/150
4/4 [==============================] - 0s 5ms/step - loss: 1.2467 - accuracy: 0.3661
Epoch 11/150
4/4 [===========

In [ ]:
new_data=[5.1,3.5,1.4,0.2]
y_pred=model.predict([new_data])

1/1 [==============================] - 0s 103ms/step


In [ ]:
print(y_pred)

[[9.5744562e-01 4.2112425e-02 4.4189449e-04]]


In [ ]:
score=model.evaluate(x_test,y_test)
print('model evaluation',score)

2/2 [==============================] - 0s 7ms/step - loss: 0.2925 - accuracy: 0.9737
model evaluation [0.292520135641098, 0.9736841917037964]
